// Native option allowlists adapted verbatim from Cockpit ee816002
// src-tauri/src/modules/codex_proxy_mihomo.rs::validate_native_proxy.
// Mihomo v1.19.31; source attribution and license: THIRD_PARTY_NOTICES.md.
export const nativeOptions:Readonly<Record<string,readonly string[]>> = {
  "ss": ["name","server","port","password","cipher","udp","plugin","plugin-opts","udp-over-tcp","udp-over-tcp-version","client-fingerprint"],
  "ssr": ["name","server","port","password","cipher","obfs","obfs-param","protocol","protocol-param","udp"],
  "socks5": ["name","server","port","username","password","tls","udp","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key"],
  "http": ["name","server","port","username","password","tls","sni","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","headers"],
  "vmess": ["name","server","port","uuid","alterId","cipher","udp","network","tls","alpn","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","servername","ech-opts","shadow-tls-opts","restls-opts","jls-opts","reality-opts","tlsmirror-opts","mekya-opts","mkcp-opts","http-opts","h2-opts","grpc-opts","ws-opts","packet-addr","xudp","packet-encoding","global-padding","authenticated-length","client-fingerprint"],
  "vless": ["name","server","port","uuid","flow","tls","alpn","udp","packet-addr","xudp","packet-encoding","encryption","network","ech-opts","shadow-tls-opts","restls-opts","jls-opts","reality-opts","http-opts","h2-opts","grpc-opts","ws-opts","xhttp-opts","ws-headers","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","servername","client-fingerprint"],
  "trojan": ["name","server","port","password","alpn","sni","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","udp","network","ech-opts","shadow-tls-opts","restls-opts","jls-opts","reality-opts","grpc-opts","ws-opts","ss-opts","client-fingerprint"],
  "hysteria": ["name","server","port","ports","protocol","obfs-protocol","up","up-speed","down","down-speed","auth","auth-str","obfs","sni","ech-opts","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","alpn","recv-window-conn","recv-window","disable-mtu-discovery","fast-open","hop-interval"],
  "hysteria2": ["name","server","port","udp","ports","hop-interval","up","down","password","obfs","obfs-password","obfs-min-packet-size","obfs-max-packet-size","sni","ech-opts","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","alpn","cwnd","bbr-profile","udp-mtu","handshake-timeout","realm-opts","initial-stream-receive-window","max-stream-receive-window","initial-connection-receive-window","max-connection-receive-window"],
  "tuic": ["name","server","port","token","uuid","password","ip","heartbeat-interval","alpn","reduce-rtt","request-timeout","udp-relay-mode","congestion-controller","disable-sni","max-udp-relay-packet-size","fast-open","max-open-streams","cwnd","bbr-profile","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","recv-window-conn","recv-window","disable-mtu-discovery","max-datagram-frame-size","sni","ech-opts","udp-over-stream","udp-over-stream-version"],
  "wireguard": ["name","ip","ipv6","private-key","workers","mtu","udp","persistent-keepalive","ip-stack","amnezia-wg-option","peers","remote-dns-resolve","dns","refresh-server-ip-interval","server","port","public-key","pre-shared-key","reserved","allowed-ips"],
  "ssh": ["name","server","port","username","password","private-key","private-key-passphrase","host-key","host-key-algorithms"],
  "snell": ["name","server","port","psk","udp","version","reuse","obfs-opts","client-fingerprint"],
  "anytls": ["name","server","port","password","alpn","sni","ech-opts","shadow-tls-opts","restls-opts","jls-opts","client-fingerprint","skip-cert-verify","name-cert-verify","fingerprint","certificate","private-key","udp","client-metadata","idle-session-check-interval","idle-session-timeout","min-idle-session","disable-reuse"],
  "mieru": ["name","server","port","port-range","transport","udp","username","password","multiplexing","handshake-mode","traffic-pattern"],
}
